import "./globals.css";
import {Share_Tech_Mono } from "next/font/google";
import {Roboto} from "next/font/google";
import { Creepster } from "next/font/google";

const russoOne = Share_Tech_Mono({
  subsets: ["latin"],
  variable: "--font-russo-one",
  weight: '400',
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: "400"
})

const creepster = Creepster({
  subsets: ["latin"],
  variable: "--font-creepster",
  weight: "400",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: " /icons8-user-48.jpg",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${russoOne.variable} ${creepster.variable}`}>
        
        {children}
      </body>
    </html>
  );
}
